NAME = 'server'
NETWORK = '172.27.11.'
PACKAGES = 'curl vim wget'

Vagrant.configure("2") do |config|
  config.vm.define "#{NAME}1" do |server1|
    server1.vm.box = "centos/8"
    server1.vm.network "private_network", ip: NETWORK + '10'
    server1.vm.provision "shell", inline: <<-SHELL
      dnf install -y httpd #{PACKAGES}
      systemctl enable httpd
      systemctl start httpd
    SHELL
  end
  config.vm.define "#{NAME}2" do |server2|
    server2.vm.box = "debian/buster64"
    server1.vm.network "private_network", ip: NETWORK + '10'
    server2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 #{PACKAGES}
    SHELL
  end

  config.vm.provision "shell", inline: <<-SHELL
    id devops
    if [ "$?" -ne 0 ]; then
      useradd -m -d /home/devops -s /bin/bash devops
    fi
  SHELL
end
