DNF = 'dnf install -y httpd'
APT = 'apt-get update && apt-get install -y apache2'

machines = {
  'server1' => { 'image' => 'centos/8', 'ip' => '10', 'shell' => DNF },
  'server2' => { 'image' => 'debian/buster64', 'ip' => '20', 'shell' => APT }
}

Vagrant.configure('2') do |config|
  machines.each do |name,conf|
    config.vm.define name do |machine|
      machine.vm.box = conf['image']
      machine.vm.network "private_network", ip: "172.27.11.#{conf['ip']}"
      machine.vm.provision 'shell', inline: <<-SHELL
        #{conf['shell']}
      SHELL
      if name == 'server2'
        machine.vm.disk :disk, name: "iscsi", size: "10GB"
      end
    end
  end
  config.vm.provision "shell", inline: <<-SHELL
    id devops
    if [ "$?" -ne 0 ]; then
      useradd -m -d /home/devops -s /bin/bash devops
    fi
  SHELL
end
